FROM node:16-alpine

ENV HOME=/app \
    LANG=C.UTF-8 \
    TZ=Asia/Tokyo \
    HOST=0.0.0.0 \
    API_URL=https://api.sharefavplace.com/

WORKDIR ${HOME}

COPY package*.json ./

RUN apk update && \
    apk upgrade && \
    apk add --no-cache make gcc g++ python3 && \
    yarn install

COPY . ./

RUN yarn run build

EXPOSE 3000
