version: '3.8'

services:
  front:
      build:
        context: .
        args:
          WORKDIR: $WORKDIR
          CONTAINER_PORT: $CONTAINER_PORT
      container_name: share_favplace_front
      command: yarn run dev
      volumes:
        - .:/$WORKDIR
      ports:
        - "$FRONT_PORT:$CONTAINER_PORT"