version: '3.8'

services:
  front:
      build:
        context: .
        dockerfile: Dockerfile.development
        args:
          WORKDIR: $WORKDIR
          CONTAINER_PORT: $CONTAINER_PORT
          API_URL: "http://localhost:$API_PORT/ShareFavplace"
      container_name: share_favplace_front
      command: yarn run dev
      volumes:
        - .:/$WORKDIR
      ports:
        - "$FRONT_PORT:$CONTAINER_PORT"