x-aws-vpc: ${AWS_VPC}
x-aws-cluster: ${AWS_ECS_CLUSTER}
x-aws-loadbalancer: ${AWS_ALB}

services:
  front:
    image: ${AWS_FRONT_IMAGE}
    env_file:
      - ./environment/front-variables-prd.env
    command: yarn run start
    ports:
      - target: ${FRONT_PORT}
        x-aws-protocol: http
    networks:
      - sharefavplacefront

networks:
  sharefavplacefront:
    external: true
    name: ${AWS_SECURITY_GROUP}

x-aws-cloudformation:
  Resources:
    Front3000TargetGroup:
      Properties:
        HealthCheckPath: /
        HealthCheckTimeoutSeconds: 30
        HealthCheckIntervalSeconds: 300
        UnhealthyThresholdCount: 5
        Matcher:
          HttpCode: 200
    Front3000Listener:
      Properties:
        Certificates:
          - CertificateArn: ${AWS_CERTIFICATE}
        Protocol: HTTPS
        Port: 443
    ALBListenerHTTP:
      Type: "AWS::ElasticLoadBalancingV2::Listener"
      Properties:
        Port: 80
        Protocol: HTTP
        DefaultActions:
          - Type: redirect
            RedirectConfig: 
              Host: '#{host}'
              Path: '/#{path}'
              Port: 443
              Protocol: HTTPS
              Query: '#{query}'
              StatusCode: HTTP_301
        LoadBalancerArn: ${AWS_ALB}